name: Trigger forks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-forks:
    name: Trigger forks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add more forks here if applicable
        repo: ['TheRealArthurDent/leakage-sensor']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl \
            --header "Accept: application/vnd.github.everest-preview+json" \
            --header "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --fail \
            --request POST \
            --data '{"event_type": "push_main", "client_payload": { "foo": "bar" }}' \
            https://api.github.com/repos/${{ matrix.repo }}/dispatches
